hisptz/react-ui

package.json
src/components/ConfigurationStepper/configurationStepper.stories.tsx
src/components/ConfigurationStepper/index.tsx
src/styles/styles.css
src/types/index.d.ts

- Fixed issues with stepper component layout

fix(Stepper Component): Fixes

---

src/components/DataConfigurationArea/DataConfigurationArea.stories.tsx
src/components/DataConfigurationArea/components/CustomAccordion/CustomAccordion.stories.tsx
src/components/DataConfigurationArea/components/CustomAccordion/index.tsx
src/components/DataConfigurationArea/components/DataSource/DataSource.stories.tsx
src/components/DataConfigurationArea/index.tsx

- Added group footer for DataConfiguration Area
- Changed padding to 8px
on the CustomAccordion children's container

feat(DataConfigurationArea): Improvements

---

src/components/ConfigurationStepper/configurationStepper.stories.tsx
src/components/ConfigurationStepper/index.tsx
src/components/ConfigurationStepper/types/props.tsx

- Added onStepChange handler to allow blocking of step change

feat(Stepper ): Implementation

---

src/components/DataSourceSelector/models/eventDataItems.ts
src/components/DataSourceSelector/models/nativeDataSource.ts

- Added shortName,name,and description to the output of the data
selector

feat(DataSourceSelector): Implementation

---

src/components/ConfigurationStepper/index.tsx
src/components/ConfigurationStepper/types/props.tsx

- Made the onNextStep function async to allow async validations

feat(Stepper): Improvements

---

.storybook/preview.js
src/components/ConfigurationStepper/configurationStepper.stories.tsx
src/components/ConfigurationStepper/configurationStepper.test.tsx
src/components/ConfigurationStepper/index.tsx
src/components/ConfigurationStepper/types/props.tsx

- exposed steps control to the parent component
- improved styling

feat(Stepper ): Improvements

---

src/components/DataConfigurationArea/DataConfigurationArea.stories.tsx
src/components/DataConfigurationArea/components/CustomAccordion/CustomAccordion.stories.tsx
src/components/DataConfigurationArea/components/CustomAccordion/components/GroupTitle.tsx
src/components/DataConfigurationArea/components/CustomAccordion/index.tsx
src/components/DataConfigurationArea/index.tsx

- Added right adornment for the accordion group title

feat(GroupTitle): Improvement

---

src/components/FormField/FormField.stories.tsx
src/components/FormField/components/Input/components/MultipleFieldsField/index.tsx
src/components/FormField/components/Input/types/index.ts

- Exposed addable and deletable components for further customizations
Signed-off-by: Gift Nnko <nnkogift@hotmail.com>

fix(MultipleFieldForm): Fix

---

src/components/FormField/components/MultipleFieldsField/index.tsx

- Added gap for multiple fields row to allow spacing with the delete
button
Signed-off-by: Gift Nnko <nnkogift@hotmail.com>

fix(MultipleFields Field): Styling fixes

---

src/components/PeriodSelector/components/CalendarSpecificPeriodDimension/components/TransferOption.tsx
src/styles/icons.css
src/styles/styles.css

fix(Period Selector): Transfer option icons
- Reduced transfer option icon size for the period selector to match DHIS2
design

fix(Period Selector): Transfer option icons

---

src/components/ConfirmDialog/ConfirmDialog.stories.tsx
src/components/ConfirmDialog/components/ConfirmDialog/index.tsx
src/components/ConfirmDialog/index.tsx

- Implemented custom actions for the confirm dialog
Resolves #39

Feature/issue #39

---

.idea/vcs.xml
src/components/DataConfigurationArea/DataConfigurationArea.stories.tsx
src/components/DataConfigurationArea/components/CustomAccordion/components/GroupTitle.tsx
src/components/DataConfigurationArea/components/CustomAccordion/index.tsx
src/components/DataConfigurationArea/index.tsx

- Fixed issue with draggable height collapsing when onDrag is active

:bug: fix(data configuration area): fixes

---

src/components/FormField/RHFFormField.stories.tsx
src/components/FormField/components/HookFormInput/index.tsx
src/components/FormField/components/LegendDefinitionField.tsx
src/components/FormField/components/LegendMinMax.tsx
src/components/FormField/components/RichTextEditor/index.tsx

- Fixed issue with mandatory settings not working for RHF input
Fixes #37

Bugfix/issue #37

---

src/components/FormField/components/MultipleFieldsField/index.tsx

- Implemented conditional adjustment of the multiple field depending on whether the delete button is showing or not
Fixes #38

:bug: fix(MultipleFields field): Fixes

---

src/components/Modals/Modal.stories.tsx
src/components/Modals/components/OrgUnitSelectorModal.tsx
src/components/Modals/components/PeriodSelectorModal.tsx

- Conditionally display plural inclusion headers to modals if singleSelection is not selected

:bug: fix(modals): Improvements

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test.yml

- Implemented build workflow on push to develop

Bugfix/issue #45

---

src/components/ConfirmDialog/ConfirmDialogProvider.stories.tsx
src/components/ConfirmDialog/components/ConfirmDialog/index.tsx
src/components/ConfirmDialog/states/dialog.ts
src/components/FormField/components/Input/index.tsx
src/components/LegendDefinitions/LegendDefinition.stories.tsx
src/components/LegendDefinitions/RHFLegendDefinition.stories.tsx
src/components/LegendDefinitions/components/AddLegendDefinition.tsx
src/components/LegendDefinitions/components/EditLegendDefinition.tsx
src/components/LegendDefinitions/components/LegendDefinitions.tsx
src/components/LegendDefinitions/components/RHF.tsx
src/components/LegendDefinitions/hooks/useManageLegendDefinitions.ts
src/components/LegendDefinitions/hooks/useResetLegends.ts
src/components/LegendDefinitions/index.tsx
src/components/LegendDefinitions/utils/index.ts

- Implemented legend definitions standalone RHF field

✨ Legend definitions field implementation

---

src/components/FormField/components/HookFormInput/index.tsx
src/components/FormField/types/index.ts
src/components/LegendDefinitions/components/RHF.tsx

- exposed control prop for RHF inputs

:bug: RHF Input Fix: Exposed `control` prop

---

i18n/en.pot
src/components/DataConfigurationArea/components/CustomAccordion/CustomAccordion.stories.tsx
src/components/DataConfigurationArea/components/CustomAccordion/components/GroupTitle.tsx
src/components/DataConfigurationArea/components/CustomAccordion/index.tsx
src/components/DataConfigurationArea/index.tsx

- Fixed issues with group-title build errors

Data configuration area group title fixes

---

package.json

- Updated package version to `v1.0.38`

:bookmark: Version update

---

package.json
src/components/FormField/components/Input/index.tsx
src/components/FormField/types/index.ts
src/components/LegendDefinitions/components/EditLegendDefinition.tsx

- Fixed issues with `postinstall` file missing during installation
- Fixed issues with types for custom input

Postinstall issues after package install

---

package.json

- include postinstall in files

fix(package.json): postinstall

---

src/components/FormField/RHFFormField.stories.tsx
src/components/FormField/components/AgeField/index.tsx
src/components/FormField/components/AgeField/utils/index.ts

- Fixed issues with age field throwing error for some date formats
- Returned ISO date string from age field input

Age Field error for various formats fixes

---

src/components/FormField/components/AgeField/index.tsx

- Fixed issues with age field not accepting min and max values on the date field
Fixes #68

:bug: fix(Age Field): Fixes

---

src/components/Modals/components/OrgUnitSelectorModal.tsx
src/components/OrgUnitSelector/OrgUnitSelector.stories.tsx
src/components/OrgUnitSelector/OrgUnitSelector.test.tsx
src/components/OrgUnitSelector/components/Selector.tsx
src/components/OrgUnitSelector/hooks/index.ts
src/components/OrgUnitSelector/services/index.ts
src/components/OrgUnitSelector/types/index.ts
src/components/OrgUnitSelector/utils/index.ts
src/styles/styles.css

- Implemented search feature for organisation unit selector, allowing search on any level of organisation unit

Feature: Organisation unit selector search

---

src/components/Modals/Modal.stories.tsx
src/components/PeriodSelector/PeriodSelector.stories.tsx
src/components/PeriodSelector/components/CalendarSpecificPeriodDimension/components/DateRange/index.tsx
src/components/PeriodSelector/components/CalendarSpecificPeriodDimension/index.tsx
src/components/PeriodSelector/components/CalendarSpecificPeriodDimension/interfaces/props.ts
src/components/PeriodSelector/components/DateRange/index.tsx
src/components/PeriodSelector/index.tsx
src/components/PeriodSelector/types/props.ts

- Implemented date range selector 
- Bug fixes & improvements on period selector

Feature: Date range on period selector

---

.storybook/main.js
cypress.config.ts
package.json
src/components/PeriodSelector/PeriodSelector.stories.tsx
src/components/PeriodSelector/index.tsx
src/components/PeriodSelector/types/props.ts
yarn.lock

- Fixed issues with selectedPeriods going to wrong period selector
- Fixed issues with storybook versions

:bug: fix(period-selector): Fixes

---

.storybook/preview.tsx
package.json
src/components/FormField/types/index.ts
src/index.ts
yarn.lock

:bug: fix(map): Fixes

---

.storybook/preview.tsx
package.json
src/components/FormField/types/index.ts
src/index.ts
yarn.lock

Revert ":bug: fix(map): Fixes"

---

package.json

chore(package.json): Version update

---

src/components/Map/components/MapArea/index.tsx
src/components/Map/components/MapLayer/components/BoundaryLayer/index.tsx
src/components/Map/components/MapLayer/components/ThematicLayer/components/Choropleth/index.tsx
src/components/Map/components/MapLayer/components/ThematicLayer/index.tsx
src/components/Map/components/MapProvider/index.tsx
src/components/Map/components/MapUpdater/index.tsx
src/components/Map/hooks/map.ts
src/components/Map/interfaces/index.ts
src/components/Map/utils/map.ts

- Code cleanup
- Fixed issues with boundaries by implementing geoJSON

fix(map): Fixes

---

src/components/Map/Map.stories.tsx
src/components/Map/components/MapProvider/index.tsx
src/components/Map/utils/map.ts
src/dataProviders/map.tsx

- Enabled org unit level selection in map

:bug: fix(map): Improvements

---

vite.config.ts

- Removed vite config that caused test errors

fix(storybook): Fixes

---

src/components/CachedOrgUnitProvider/OfflineOrgUnitProvider.stories.tsx
src/components/CachedOrgUnitProvider/index.tsx
src/index.ts

- Exported the caching components, hooks, and services

:bug: fix(caching-org-unit): Fixes

---

.storybook/preview.tsx
i18n/en.pot
package.json
src/components/CachedOrgUnitProvider/hooks/index.ts
src/components/CachedOrgUnitProvider/services/db.ts
src/components/Map/Map.stories.tsx
yarn.lock

- Improved how caching is validated

fix(cached-org-unit): Improvements

---

src/components/CachedOrgUnitProvider/OfflineOrgUnitProvider.stories.tsx
src/components/CachedOrgUnitProvider/hooks/index.ts
src/components/CachedOrgUnitProvider/index.tsx
src/components/CachedOrgUnitProvider/utils/index.ts

- Added a prop to control the page size of getting org units initially
Fixes #128

feat(cached-org-unit): Improvements

---

src/components/Map/Map.stories.tsx
src/components/Map/components/MapLayer/components/LegendArea/index.tsx
src/components/Map/components/MapLayer/components/PointLayer/components/PointLegend/index.tsx
src/components/Map/components/MapLayer/components/PointLayer/index.tsx
src/components/Map/components/MapLayer/components/ThematicLayer/components/Bubble/components/BubbleLegend/index.tsx
src/components/Map/components/MapLayer/components/ThematicLayer/components/Bubble/index.tsx
src/components/Map/components/MapLayer/components/ThematicLayer/index.tsx
src/components/Map/components/MapLayer/interfaces/index.ts
src/components/Map/utils/helpers.ts

Fixed issues with selected icon does not reflect for point layer configuration Fixes #129
Added radius configuration prop for bubble layer Fixes #130

fix(map): Fixes and Improvements

---

src/components/Map/Map.stories.tsx
src/components/Map/components/MapArea/index.tsx
src/components/Map/components/MapLayer/components/ThematicLayer/components/Choropleth/index.tsx
src/components/Map/components/MapLayer/components/ThematicLayer/index.tsx
src/components/Map/components/MapLayer/index.tsx

- Changed order of appearance of map layers, making the top most on the list with the most priority
Fixes #133

feat(map layers): Improvements

---

i18n/en.pot
src/components/Map/components/EarthEngineLayerConfiguration/index.tsx

- Fixed issues with earth engine config component having infinite rerenders

fix(earth engine layer config): Fixes

---

i18n/en.pot
src/components/Map/components/EarthEngineLayerConfiguration/EarthEngineLayerConfiguration.stories.tsx
src/components/Map/components/EarthEngineLayerConfiguration/index.tsx
src/components/Map/components/ThematicLayerConfiguration/index.tsx

- Fixed issues with map configuration components

fix(map config): Fixes

---

src/components/OrgUnitSelector/components/OrgUnitTree/index.tsx

- Fixed issues with limit to selections not working

fix(org-unit-selector): Fixes

---

src/components/OrgUnitSelector/OrgUnitSelector.stories.tsx
src/components/OrgUnitSelector/components/Selector.tsx
src/components/OrgUnitSelector/hooks/index.ts
src/components/OrgUnitSelector/types/index.ts

- Implemented roots org unit prop

feat(org-unit-selector): Implementation

---

package.json
src/components/Map/Map.stories.tsx
src/components/Map/components/MapArea/index.tsx
src/components/Map/components/MapArea/interfaces/index.ts
src/components/Map/components/MapControls/components/DownloadControl/index.tsx
src/components/Map/components/MapControls/index.tsx
src/types/index.d.ts
yarn.lock

feat(map download): Implementation
